# plugin default config


#   [========== ADMIN ==========]
# log excluded advancements to console
log-excluded: true


#   [========== GAMEPLAY ==========]
# set this to change join/leave messages to a more subtle message
# player TestPlayer joins : → TestPlayer
# player TestPlayer leaves : ← TestPlayer
#   default : true
discreet-connections: true

# set this to change death messages to a more subtle message (default message but in gray)
#   default : true
discreet-death-messages: true

# the name of the world (main, usually the overworld dimension) where the game is played
#   DISABLED : CREATES NETHER LINKING BUG and I don't want to mess with connection nether to world for the moment
#game-world-name:

# auto gamerule and difficulty attribution
disable-fire-spread: true
difficulty-hard: true
keep-inventory: false
no-natural-health-regen: false

# the "radius" of the square platform generated at the spawn
# if set to 0 the platform won't generate
#   default : 24
spawn-platform-radius: 24
# the height over the sea level (63) at which the spawn platform will generate
# if "spawn-platform-radius" = 0 players will still spawn at the specified height
#   default : 96
spawn-platform-height: 96
# enable waiting room minigame (a simple tag game to wait for the game to fill up)
#   default : true
enable-waiting-room-minigame: true

# the "radius" of the square where the teams will be spread when the game starts
# set to -1 to calculate the radius for which teams are separated by exactly one "server render distance" amount of blocks (only works if random-spread is false)
#   default : 256
spread-teams-radius: 256
# if the team should be randomly spread inside this radius or if they should be evenly
# spaced on a circle around the spawn (circle radius = "spread-teams-radius")
#   default : false
random-spread: false

# if you want multi-world support for a team selection lobby (pregame lobby) and a winner announcement lobby
multi-world:
  enabled: false
  # lobby/spawn world name and spawnpoint coordinates, name "arush-spawn" by default
  spawn-world-name: arush-spawn
  spawn-X: 0
  spawn-Y: 64
  spawn-Z: 0
  # name of the world for the lobby where players are teleported after the game's end and spawnpoint coordinates, name "arush-win" by default
  win-world-name: arush-win
  win-X: 0
  win-Y: 64
  win-Z: 0

#   GAME END SEQUENCE
# should there be the ranks' revelation animation (I don't know why one would disable that (?_?) )
#   default : true
ranks-revelation: true
# when the game ends players are all usually tp back to some sort of lobby
group-back:
  # should the plugin handle players when the game is ended or is it handled by another plugin / admin ?
  # "true" to use AdvancementRush end game management (next 3 options)
  #   default : true
  enabled: true
  # delay after which players are tp back (in seconds)
  #   default : 5
  delay: 5
  # where should the plugin teleport players ?
  # LOBBY : teleport them back to the same lobby where they started the game (the floating invisible box generated on team selection)
  # WORLD : if you enabled multi-world support this will try to teleport them to the world specified in "win-world-name", if it fails it will send them to LOBBY
  # allowed values are : WORLD, LOBBY
  #   default : LOBBY
  tp-destination: LOBBY

# set this to change how the game ends (win condition)
#   allowed values are : TIMER, VALUE, HYBRID
#   TIMER : the game ends on a timer and the team with the most points at the end win the game
#   VALUE : the game ends when a team reach a certain value -> first team to xxx points
#   HYBRID : a mix of both gamemodes, ends when a team reach a certain value or if no one reach the value in time
#            the winner team is the one with the most points at the end of the timer
#   default: TIMER
gamemode: TIMER

timer-options:
  # duration of the game (in minutes)
  #   default : 240 (4h)
  duration: 240
  # if you want players to be able to see the scores in the scoreboard
  # this does not disable the display of ranking
  #   default: true
  show-scores: true
  # hide the ranks in the scoreboard x minutes before the game end (in minutes)
  # set to 0 to disable
  #   default: 30
  hide-ranks-timer: 30

value-options:
  # the goal value teams must reach to win the game
  #   default: 1000
  target-value: 1000

hybrid-options:
  # the goal value teams must reach to win the game
  #   default:1000
  target-value: 1000
  # duration of the game in minutes
  #   default : 120 (2h)
  duration: 120
  # hide the scores in the scoreboard x minutes before the game end (in minutes)
  # set to 0 to disable
  #   default: 30
  hide-ranks-timer: 30
  # if you want players to be able to see the scores in the scoreboard
  # this does not disable the display of ranking
  #   default: true
  show-scores: true

# since the dragon egg advancement is almost granted when you kill the dragon and is a unique item
# you can enable a different way of earning points with it : earning points for holding it
# OR the team which hold the dragon egg at the end of the game earns its points.
# The advantage of earning points for holding it through the game is that players cannot hide
# the egg in a chest until the game end and are forced to play with it
dragon-egg-bonus:
  # enable the feature
  # enabling it makes the advancement worth 5 points, you can earn points through the 2 new modes
  enabled: true
  # way of earning points
  # HOLD : earn points for holding it, you earn a fixed amount of points for each minute you have the egg in your inventory
  # END : the player (team) which has the egg in its INVENTORY at the end of the game earn the total amount of points of the egg
  bonus-mode: HOLD
  # number of points a team earn per minute for having the dragon egg in one of its players inventory if bonus-mode is HOLD
  #   default: 10
  hold-points-per-minute: 10
  # number of points a team earn for having the dragon egg in one of its players inventory at the end of the game if bonus-mode is END
  #   default: 300
  end-bonus-points: 300
  # show the coordinate of the player holding the dragon egg in the tablist
  #   default: true
  show-coordinates: true
  # number of minutes before the game end at which the player holding the dragon egg gain the Glowing potion effect
  # set to 0 to disable
  #   default : 30
  glowing-timer: 30


#   [========== INTERFACE ==========]
# maximum of team displayed in the scoreboard "top teams" section
#   range : (1-7)
#   set 0 if you want to disable this category entirely
#     default: 5
ranking-size: 5
# show points, this does not disable the ranking
#   default: true
show-points: true


#   [========== DISCORD BOT ==========]
# your bot token got from https://discord.com/developers/applications
# NEVER SHARE THIS TOKEN ON THE INTERNET
# follow this tutorial if you want to know how to get it and create a Discord bot : https://discordpy.readthedocs.io/en/stable/discord.html
# for the sake of simplicity please give the Administrator perm to the bot, otherwise many features will not work
discord-bot-token:
# ID of the server where your instance of the bot is primarily used if you want it to try to auto connect on server start, if blank you will have to connect the bot to your Discord server using /arlink
discord-server-id:
# the default key to link Discord bot and Minecraft plugin used in /arlink (can be left blank if "discord-server-id" is specified or if you want to add it yourself with /arlink <key>)
discord-link-key:
# the main voice channel where players are waiting for the game to start
discord-general-voice-id:

# should the discord bot move automatically users on game start from voice channel specified by "discord-general-voice-id" to their team channel ?
#   default : true
start-auto-move: true
# same thing as above but this time moving members back to the general channel on game end
#   default : true
end-auto-move: true

#   [========== ADVANCEMENTS ==========]
# bonus when a team is the first one to unlock an advancement
#   default: 5
pioneer-bonus: 5
# ignored namespaces
# use this to ignore completely advancements from a plugin/vanilla. This list prevent them from being
# earned in game
# a namespace is the text before the ":" in advancements IDs -> "minecraft:story/mine_diamond" -> namespace = minecraft
# exemple to disable all vanilla advancements :
#   ignored-namespaces:
#     - "minecraft"
ignored-namespaces:
# special bonus for the first team to reach certain advancements (user defined)
# example config :
# special-bonuses:
#   "minecraft:story/enter_the_nether": 100
#   "minecraft:story/mine_diamond": 100
special-bonuses:
# edit advancements values or add new ones
# format : namespace:category/advancement
advancements-values:
# set here root advancements
#   these advancements are automatically unlocked and are used to show the player
#   the different categories and advancements
auto-unlock:
  - "minecraft:story/root"
  - "minecraft:end/root"
  - "minecraft:nether/root"
  - "minecraft:husbandry/root"
  - "minecraft:adventure/root"