name: AdvancementRush
version: '${project.version}'
main: com.github.sawors.Main
api-version: 1.18
authors: [ Sawors ]
commands:
  arteam:
    usage: /<command> <action> <parameters>
    aliases: [advancementrushteam]
  artest:
    usage: /<command>
    aliases: [advancementrushtest]
  arnick:
    usage: /<command> <nickname> or /<command> <player> <nickname>
  arunnick:
    usage: /<command> <player>
  artime:
    usage: /<command> <action> <parameter>
  arlink:
    usage: /<command> <key>
  arme:
    usage: /<command>
  arvoc:

